// ─── PackMockup Template Data ────────────────────────────────
'use strict';

const MOCKUPS_DATA = [
  {
    id: 'tuck-box',
    name: 'Tuck End Box',
    category: 'boxes',
    tags: ['box', 'retail', 'tuck', 'packaging'],
    popular: true,
    new: false,
    variants: [
      { id: 'white',  name: 'White',       color: '#f2f2f2' },
      { id: 'kraft',  name: 'Kraft',       color: '#c8a97c' },
      { id: 'black',  name: 'Black',       color: '#1c1c1c' },
      { id: 'navy',   name: 'Navy Blue',   color: '#1a2a6c' },
      { id: 'forest', name: 'Forest',      color: '#2d5a27' },
      { id: 'rose',   name: 'Rose',        color: '#c4607e' },
    ],
    description: 'Standard tuck-end retail packaging box',
    render: 'tuck-box',
  },
  {
    id: 'mailer-box',
    name: 'Mailer Box',
    category: 'boxes',
    tags: ['box', 'mailer', 'ecommerce', 'shipping'],
    popular: true,
    new: false,
    variants: [
      { id: 'white', name: 'White',  color: '#f2f2f2' },
      { id: 'kraft', name: 'Kraft',  color: '#c8a97c' },
      { id: 'black', name: 'Black',  color: '#1c1c1c' },
      { id: 'teal',  name: 'Teal',   color: '#1a6c5a' },
    ],
    description: 'E-commerce mailer box with bold isometric view',
    render: 'mailer-box',
  },
  {
    id: 'square-box',
    name: 'Square Gift Box',
    category: 'boxes',
    tags: ['box', 'square', 'gift'],
    popular: false,
    new: false,
    variants: [
      { id: 'white',  name: 'White',     color: '#f2f2f2' },
      { id: 'black',  name: 'Black',     color: '#1c1c1c' },
      { id: 'pink',   name: 'Pink',      color: '#f4a7b9' },
      { id: 'gold',   name: 'Gold',      color: '#c9a227' },
    ],
    description: 'Square gift packaging box isometric view',
    render: 'square-box',
  },
  {
    id: 'standup-pouch',
    name: 'Stand-up Pouch',
    category: 'pouches',
    tags: ['pouch', 'bag', 'food', 'zipper', 'doypack'],
    popular: true,
    new: false,
    variants: [
      { id: 'white',    name: 'White',       color: '#f5f5f5' },
      { id: 'silver',   name: 'Silver Foil', color: '#b8b8c0' },
      { id: 'kraft',    name: 'Kraft',       color: '#c8a97c' },
      { id: 'black',    name: 'Black',       color: '#1c1c1c' },
      { id: 'rosegold', name: 'Rose Gold',   color: '#b5767a' },
    ],
    description: 'Stand-up pouch with zipper closure',
    render: 'standup-pouch',
  },
  {
    id: 'flat-pouch',
    name: 'Flat Sachet',
    category: 'pouches',
    tags: ['sachet', 'flat', 'pouch', 'seal'],
    popular: false,
    new: false,
    variants: [
      { id: 'white',  name: 'White',       color: '#f5f5f5' },
      { id: 'silver', name: 'Silver Foil', color: '#b8b8c0' },
      { id: 'kraft',  name: 'Kraft',       color: '#c8a97c' },
      { id: 'black',  name: 'Black',       color: '#1c1c1c' },
    ],
    description: 'Flat sachet pouch with heat-sealed edges',
    render: 'flat-pouch',
  },
  {
    id: 'soda-can',
    name: 'Beverage Can',
    category: 'cans',
    tags: ['can', 'beverage', 'drink', 'cylinder', 'aluminum'],
    popular: true,
    new: false,
    variants: [
      { id: 'silver', name: 'Aluminum',    color: '#aaaaaa' },
      { id: 'white',  name: 'White',       color: '#f0f0f0' },
      { id: 'black',  name: 'Matte Black', color: '#1c1c1c' },
      { id: 'gold',   name: 'Gold',        color: '#c9a227' },
    ],
    description: 'Cylindrical beverage can with label wrap',
    render: 'soda-can',
  },
  {
    id: 'paper-cup',
    name: 'Paper Cup',
    category: 'cups',
    tags: ['cup', 'coffee', 'drink', 'paper', 'tapered'],
    popular: true,
    new: false,
    variants: [
      { id: 'white', name: 'White', color: '#f5f5f5' },
      { id: 'kraft', name: 'Kraft', color: '#c8a97c' },
      { id: 'black', name: 'Black', color: '#1c1c1c' },
    ],
    description: 'Tapered paper cup with sleeve band',
    render: 'paper-cup',
  },
  {
    id: 'cosmetic-jar',
    name: 'Cosmetic Jar',
    category: 'jars',
    tags: ['jar', 'cosmetic', 'cream', 'skincare', 'beauty'],
    popular: true,
    new: false,
    variants: [
      { id: 'white',  name: 'White',      color: '#f5f5f5' },
      { id: 'black',  name: 'Black',      color: '#1c1c1c' },
      { id: 'gold',   name: 'Gold',       color: '#c9a227' },
      { id: 'pink',   name: 'Blush Pink', color: '#e8b4c0' },
      { id: 'green',  name: 'Sage',       color: '#8faa8f' },
    ],
    description: 'Wide-mouth cosmetic jar with lid',
    render: 'cosmetic-jar',
  },
  {
    id: 'spray-bottle',
    name: 'Spray Bottle',
    category: 'bottles',
    tags: ['bottle', 'spray', 'pump', 'skincare', 'mist'],
    popular: false,
    new: true,
    variants: [
      { id: 'white',   name: 'White',        color: '#f5f5f5' },
      { id: 'black',   name: 'Black',        color: '#1c1c1c' },
      { id: 'frosted', name: 'Frosted',      color: '#d4dce4' },
      { id: 'amber',   name: 'Amber',        color: '#b87333' },
    ],
    description: 'Pump spray bottle for cosmetics',
    render: 'spray-bottle',
  },
  {
    id: 'shopping-bag',
    name: 'Shopping Bag',
    category: 'bags',
    tags: ['bag', 'shopping', 'retail', 'paper', 'carry'],
    popular: false,
    new: false,
    variants: [
      { id: 'white', name: 'White', color: '#f5f5f5' },
      { id: 'kraft', name: 'Kraft', color: '#c8a97c' },
      { id: 'black', name: 'Black', color: '#1c1c1c' },
      { id: 'navy',  name: 'Navy',  color: '#1a2a6c' },
    ],
    description: 'Paper shopping bag with rope handles',
    render: 'shopping-bag',
  },
];

const CATEGORIES = [
  { id: 'all',      name: 'All',             icon: 'grid' },
  { id: 'boxes',    name: 'Boxes',           icon: 'box' },
  { id: 'pouches',  name: 'Pouches & Bags',  icon: 'package' },
  { id: 'cans',     name: 'Cans',            icon: 'cylinder' },
  { id: 'cups',     name: 'Cups',            icon: 'cup' },
  { id: 'jars',     name: 'Jars',            icon: 'jar' },
  { id: 'bottles',  name: 'Bottles',         icon: 'bottle' },
  { id: 'bags',     name: 'Shopping Bags',   icon: 'bag' },
];
